package com.soc.backend_core.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;
import java.util.Map;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class UnifiedEvent {

    private String eventId;         // unique ID generated by us
    private String deviceId;        // which machine sent this
    private String eventType;       // process_start, dns_query, login_fail...
    private String sourceIp;        // where the traffic came from
    private String destinationIp;   // where the traffic is going
    private String process;         // process name if EDR event
    private String user;            // which user triggered this
    private String severity;        // LOW, MEDIUM, HIGH
    private String source;          // NDR or EDR
    private Instant timestamp;      // when it happened
    private Map<String, Object> raw; // original payload as-is
}